@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

' Print Layout
LAYOUT_WITH_LEGEND()
LAYOUT_LEFT_RIGHT()
'LAYOUT_TOP_DOWN()

' Print Diagram Title
title System Context Diagram for Patient Portal System \n

' Assign Variables
Person_Ext(patient, "Patient \n [Person]", "A patient of a clinic with a patient user account.")
System_Ext(mail_system, "Web E-mail System \n [System]", "Third-Party e-mail system.")

' Patient Portal Boundary
System_Boundary(bPP, "Medical Office") {
    System_Boundary(portal, "Patient Portal App") {
    System(portalApp, "Patient Portal App \n [Application]", "Delivers web content.")
    System(API, "API \n [Application]", "Provides app functionality.")
    System(database, "Database \n [Database]", "Stores user registration information and access logs.")
    }
    Person(records, "Records Personnel \n [Person]", "Uploads patient information.")
}

' Print Relationships
Rel(records, portalApp, "Uploads patient info", "[HTTPS]")
Rel(patient, portalApp, "Uses", "[HTTPS]")
Rel(portalApp, mail_system, "Sends notification e-mail", "[SMTP]")
Rel(patient, mail_system, "Reads e-mail", "[HTTPS]")
Rel(API, database, "Reads and writes data", "[JDBC]")
Rel(portalApp, API, "Makes API calls", "[JSON/HTTPS]")

@enduml
